=== fraunhoferfokus/gemo/src/testDataGenerator/db.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.fokus.fraunhofer.de" xmlns="http://www.fokus.fraunhofer.de">

	<xs:element name="dataset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="schema_dsc" minOccurs="1" maxOccurs="1" />
				<xs:element ref="data" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="data">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="timestamp" />
				<xs:element ref="text" />
				<xs:element ref="integer" />
				<xs:element ref="float" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="schema_dsc">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="timestamp" />
				<xs:element ref="text" />
				<xs:element ref="integer" />
				<xs:element ref="float" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="timestamp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:dateTime">
					<xs:attribute name="field" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="integer">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="field" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="float">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="field" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="text">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="field" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="string">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9_-])*" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== fraunhoferfokus/gemo/src/mobility-services/storage/src/test/members.xml
<?xml version="1.0" encoding="UTF-8"?>

<dataset xmlns="http://www.fokus.fraunhofer.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.fokus.fraunhofer.de ../main/resources/db.xsd">

    <schema_dsc>
        <timestamp field="geburtstag">2002-05-30T09:30:10.5</timestamp>
        <text field="vorname">Max</text>
        <integer field="alter">25</integer>
        <float field="reichtum">1024.55</float>
    </schema_dsc>

    <data>
        <timestamp field="geburtstag">2012-05-30T09:30:10.5</timestamp>
        <text field="vorname">Erika</text>
        <integer field="alter">25</integer>
        <float field="reichtum">1024.55</float>
    </data>
	
    <data>
        <timestamp field="geburtstag">2012-05-30T09:30:10.5</timestamp>
        <text field="vorname">Erika</text>
        <integer field="alter">22</integer>
        <float field="reichtum">50.5555</float>
    </data>

</dataset>

=== fraunhoferfokus/gemo/src/mobility-services/storage/src/test/eStation1.xml
<?xml version="1.0" encoding="UTF-8"?>

<dataset xmlns="http://www.fokus.fraunhofer.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fokus.fraunhofer.de ../main/resources/db.xsd">

    <schema_dsc>
        <timestamp field="buildDate">2012-05-30T09:30:10.5</timestamp>
        <text field="operator">eTexnix</text>
        <float field="pricePerKiloWattHour">0.12</float>
        <text field="currency">eur</text>
        <float field="lon">52.515489</float>
        <float field="lat">13.370189</float>
    </schema_dsc>

	<data>
        <timestamp field="buildDate">2012-05-30T09:30:10.5</timestamp>
        <text field="operator">eTexnix</text>
        <float field="pricePerKiloWattHour">0.12</float>
        <text field="currency">eur</text>
        <float field="lon">52.515489</float>
        <float field="lat">13.370189</float>
    </data>

</dataset>
